version: "3.8"
services:
  tfg-api:
    container_name: tfg-api
    build:
      context: tfg-api
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    labels:
      - "com.docker.compose.container-number=1"
    volumes:
      - ./tfg-api:/src
      - /src/node_modules
  tfg-app-web:
    container_name: tfg-app-web
    build:
      context: tfg-app-web
    command: npm run start
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-ember:*
    labels:
      - "com.docker.compose.container-number=1"
    depends_on:
      - tfg-api
    volumes:
      - ./tfg-app-web:/app
      - /src/node_modules
